version: "3"

services:
  # app:
  #   container_name: covid19-tracker-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   stdin_open: true
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./src:/app/src
  #     - ./public:/app/public
  #   env_file:
  #     - .env
  
  app-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    # build: nginx
    # image: nginx:1.24.0
    container_name: covid19-tracker-app-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      # - ./build/:/app/build/
      # - ./public/:/usr/share/nginx/html/public/
    
    # docker cp covid19-tracker-app:/app/build ./build
