version: '3'
services:
  covid19-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3000"
    container_name: covid19-tracker-app
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env