version: "3"

services:
  app:
    container_name: covid19-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env
